################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_SRCS := 
C++M_SRCS := 
C++_SRCS := 
CCM_SRCS := 
CC_SRCS := 
CPP_SRCS := 
CXXM_SRCS := 
CXX_SRCS := 
C_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
O_SRCS := 
SX_SRCS := 
S_UPPER_SRCS := 
C++M_DEPS := 
C++_DEPS := 
CCM_DEPS := 
CC_DEPS := 
CPP_DEPS := 
CXXM_DEPS := 
CXX_DEPS := 
C_DEPS := 
C_UPPER_DEPS := 
EXECUTABLES := 
OBJS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
3rdparty/libcrc/src \
apps/bundle_deploy \
apps/cpp_rpc \
apps/dso_plugin_module \
apps/extension/src \
apps/howto_deploy \
apps/rocm_rpc \
build/CMakeFiles/3.31.6/CompilerIdC \
build/CMakeFiles/3.31.6/CompilerIdCXX \
build/CMakeFiles/tvm_objs.dir/src/arith \
build/CMakeFiles/tvm_objs.dir/src/auto_scheduler \
build/CMakeFiles/tvm_objs.dir/src/auto_scheduler/search_policy \
build/CMakeFiles/tvm_objs.dir/src/autotvm \
build/CMakeFiles/tvm_objs.dir/src/driver \
build/CMakeFiles/tvm_objs.dir/src/ir \
build/CMakeFiles/tvm_objs.dir/src/node \
build/CMakeFiles/tvm_objs.dir/src/parser \
build/CMakeFiles/tvm_objs.dir/src/printer \
build/CMakeFiles/tvm_objs.dir/src/relay/analysis \
build/CMakeFiles/tvm_objs.dir/src/relay/backend \
build/CMakeFiles/tvm_objs.dir/src/relay/backend/vm \
build/CMakeFiles/tvm_objs.dir/src/relay/ir \
build/CMakeFiles/tvm_objs.dir/src/relay/op/algorithm \
build/CMakeFiles/tvm_objs.dir/src/relay/op/annotation \
build/CMakeFiles/tvm_objs.dir/src/relay/op \
build/CMakeFiles/tvm_objs.dir/src/relay/op/dyn/algorithm \
build/CMakeFiles/tvm_objs.dir/src/relay/op/dyn/image \
build/CMakeFiles/tvm_objs.dir/src/relay/op/dyn/nn \
build/CMakeFiles/tvm_objs.dir/src/relay/op/dyn/tensor \
build/CMakeFiles/tvm_objs.dir/src/relay/op/image \
build/CMakeFiles/tvm_objs.dir/src/relay/op/memory \
build/CMakeFiles/tvm_objs.dir/src/relay/op/nn \
build/CMakeFiles/tvm_objs.dir/src/relay/op/tensor \
build/CMakeFiles/tvm_objs.dir/src/relay/op/vision \
build/CMakeFiles/tvm_objs.dir/src/relay/op/vm \
build/CMakeFiles/tvm_objs.dir/src/relay/qnn/op \
build/CMakeFiles/tvm_objs.dir/src/relay/qnn/pass \
build/CMakeFiles/tvm_objs.dir/src/relay/qnn \
build/CMakeFiles/tvm_objs.dir/src/relay/quantize \
build/CMakeFiles/tvm_objs.dir/src/relay/transforms \
build/CMakeFiles/tvm_objs.dir/src/runtime/stackvm \
build/CMakeFiles/tvm_objs.dir/src/support \
build/CMakeFiles/tvm_objs.dir/src/target \
build/CMakeFiles/tvm_objs.dir/src/target/datatype/myfloat \
build/CMakeFiles/tvm_objs.dir/src/target/datatype \
build/CMakeFiles/tvm_objs.dir/src/target/opt \
build/CMakeFiles/tvm_objs.dir/src/target/source \
build/CMakeFiles/tvm_objs.dir/src/target/stackvm \
build/CMakeFiles/tvm_objs.dir/src/te/autodiff \
build/CMakeFiles/tvm_objs.dir/src/te/operation \
build/CMakeFiles/tvm_objs.dir/src/te/schedule \
build/CMakeFiles/tvm_objs.dir/src/te \
build/CMakeFiles/tvm_objs.dir/src/tir/analysis \
build/CMakeFiles/tvm_objs.dir/src/tir/ir \
build/CMakeFiles/tvm_objs.dir/src/tir/op \
build/CMakeFiles/tvm_objs.dir/src/tir/transforms \
build/CMakeFiles/tvm_objs.dir/src/topi \
build/CMakeFiles/tvm_runtime_objs.dir/src/runtime \
build/CMakeFiles/tvm_runtime_objs.dir/src/runtime/contrib/random \
build/CMakeFiles/tvm_runtime_objs.dir/src/runtime/contrib/sort \
build/CMakeFiles/tvm_runtime_objs.dir/src/runtime/graph \
build/CMakeFiles/tvm_runtime_objs.dir/src/runtime/rpc \
build/CMakeFiles/tvm_runtime_objs.dir/src/runtime/vm \
golang/src \
jvm/native/src/main/native \
nnvm/src/c_api \
nnvm/src/core \
nnvm/src/pass \
nnvm/tests/cpp \
src/arith \
src/auto_scheduler \
src/auto_scheduler/search_policy \
src/autotvm \
src/contrib/hybrid \
src/contrib/tf_op \
src/driver \
src/ir \
src/node \
src/parser \
src/printer \
src/relay/analysis \
src/relay/backend \
src/relay/backend/contrib/arm_compute_lib \
src/relay/backend/contrib/codegen_c \
src/relay/backend/contrib/dnnl \
src/relay/backend/contrib/ethosn \
src/relay/backend/vm \
src/relay/ir \
src/relay/op/algorithm \
src/relay/op/annotation \
src/relay/op \
src/relay/op/dyn/algorithm \
src/relay/op/dyn/image \
src/relay/op/dyn/nn \
src/relay/op/dyn/tensor \
src/relay/op/image \
src/relay/op/memory \
src/relay/op/nn \
src/relay/op/tensor \
src/relay/op/vision \
src/relay/op/vm \
src/relay/qnn/op \
src/relay/qnn/pass \
src/relay/qnn \
src/relay/quantize \
src/relay/transforms \
src/runtime \
src/runtime/contrib/arm_compute_lib \
src/runtime/contrib/cblas \
src/runtime/contrib/cublas \
src/runtime/contrib/cudnn \
src/runtime/contrib/dnnl \
src/runtime/contrib/edgetpu \
src/runtime/contrib/ethosn \
src/runtime/contrib/miopen \
src/runtime/contrib/nnpack \
src/runtime/contrib/onnx \
src/runtime/contrib/random \
src/runtime/contrib/rocblas \
src/runtime/contrib/sort \
src/runtime/contrib/tflite \
src/runtime/crt/common \
src/runtime/crt/graph_runtime \
src/runtime/crt/host \
src/runtime/crt/utvm_rpc_common \
src/runtime/crt/utvm_rpc_server \
src/runtime/cuda \
src/runtime/graph/debug \
src/runtime/graph \
src/runtime/hexagon \
src/runtime/hexagon/sim/driver \
src/runtime/hexagon/sim \
src/runtime/hexagon/target/fastrpc/src \
src/runtime/hexagon/target \
src/runtime/micro \
src/runtime/micro/standalone \
src/runtime/minrpc/posix_popen_server \
src/runtime/opencl/aocl \
src/runtime/opencl \
src/runtime/opencl/sdaccel \
src/runtime/rocm \
src/runtime/rpc \
src/runtime/stackvm \
src/runtime/vm \
src/runtime/vm/profiler \
src/runtime/vulkan \
src/support \
src/target \
src/target/datatype/myfloat \
src/target/datatype/posit \
src/target/datatype \
src/target/llvm \
src/target/opt \
src/target/source \
src/target/spirv \
src/target/stackvm \
src/te/autodiff \
src/te/operation \
src/te/schedule \
src/te \
src/tir/analysis \
src/tir/ir \
src/tir/op \
src/tir/transforms \
src/topi \
tests/cpp \
tests/crt \
vta/runtime \
web/emcc \

